# Generated by Django 5.1.6 on 2025-03-23 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatgroup_groupmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatgroup',
            old_name='group_name',
            new_name='name',
        ),
    ]
