# Generated by Django 5.1.6 on 2025-03-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_group_name_chatgroup_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmessage',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='body',
            field=models.CharField(),
        ),
    ]
