# Generated by Django 5.1.6 on 2025-03-23 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_groupmessage_options_alter_groupmessage_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmessage',
            options={'ordering': ['-created']},
        ),
    ]
