# Generated by Django 5.1.6 on 2025-03-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_groupmessage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='body',
            field=models.CharField(max_length=1000),
        ),
    ]
